/**
 * Management of trading bots
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ColumnsName = 'TRADEDATE' | 'OPEN' | 'CLOSE' | 'HIGH' | 'LOW' | 'VOLUME';

export const ColumnsName = {
    Tradedate: 'TRADEDATE' as ColumnsName,
    Open: 'OPEN' as ColumnsName,
    Close: 'CLOSE' as ColumnsName,
    High: 'HIGH' as ColumnsName,
    Low: 'LOW' as ColumnsName,
    Volume: 'VOLUME' as ColumnsName
};

