/**
 * Management of trading bots
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetadataItem } from './metadataItem';


export interface Metadata { 
    TRADEDATE?: MetadataItem | null;
    OPEN?: MetadataItem | null;
    CLOSE?: MetadataItem | null;
    HIGH?: MetadataItem | null;
    LOW?: MetadataItem | null;
    VOLUME?: MetadataItem | null;
}

