/**
 * Management of trading bots
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Period } from './period';


export interface Params { 
    treningAsset: number;
    treningDate: Period;
    testingAsset: number;
    testingDate: Period;
    sequenceLength: number;
    normalise: boolean;
    numberEpochs: number;
    batchSize: number;
    loss: string;
    optimizer: string;
}

