/**
 * Management of trading bots
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DenseClass } from './denseClass';
import { LstmClass } from './lstmClass';
import { DropoutClass } from './dropoutClass';


export interface SettingsLayersInner { 
    type?: string;
    neurons: number;
    input_timesteps?: number;
    input_dim?: number;
    return_seq: boolean;
    rate: number;
    activation?: string;
}

